name: PROGPART1ANDPART2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # List contents of the root directory
      - name: List contents
        run: ls

      # Compile classes to test
      - name: Compile classes
        working-directory: ./src
        run: javac -cp "../testresources/junit-platform-console-standalone-1.6.0.jar" ./part/pkg1/and/part/pkg2/TaskList.java ./part/pkg1/and/part/pkg2/Task.java ./part/pkg1/and/part/pkg2/UserAuthentication.java "../test/part/pkg1/and/part/pkg2/TaskListTest.java" "../test/part/pkg1/and/part/pkg2/TaskTest.java" "../test/part/pkg1/and/part/pkg2/UserAuthenticationTest.java"

      # List contents of src directory to verify that classes compiled
      - name: List contents of src directory after compile
        working-directory: ./src/part/pkg1/and/part/pkg2
        run: ls
        
      # Copy compiled classes to test directory
      - name: Copy compiled classes to testresources directory
        working-directory: ./src/part/pkg1/and/part/pkg2
        run: cp -t "../../../test/part/pkg1/and/part/pkg2" TaskList.class Task.class UserAuthentication.class
        
      # Copy compiled test classes to testresources directory
      - name: Copy compiled Test classes to testresources directory
        working-directory: ./test/part/pkg1/and/part/pkg2
        run: cp -t "../../../testresources/" TaskListTest.class TaskTest.class UserAuthenticationTest.class
        
      # List contents of test package
      - name: List contents of test package
        working-directory: ./test/part/pkg1/and/part/pkg2
        run: ls
        
      # Run TaskListTest Class tests and output report
      - name: Run TaskListTest Class tests and create report
        working-directory: ./test
        run: |
          ls
          java -jar "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class part.pkg1.and.part.pkg2.TaskListTest
         
      # Run TaskTest Class tests and output report
      - name: Run TaskTest Class tests and create report
        working-directory: ./test
        run: |
          ls
          java -jar "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class part.pkg1.and.part.pkg2.TaskTest

      # Run UserAuthenticationTest Class tests and output report
      - name: Run UserAuthenticationTest Class tests and create report
        working-directory: ./test
        run: |
          ls
          java -jar "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class part.pkg1.and.part.pkg2.UserAuthenticationTest
